# base image
FROM node:15.12.0 as build

# set working directory
WORKDIR /app

RUN npm rebuild node-sass

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install

# add app
COPY . /app

# generate build
RUN npm run build

# base image
FROM nginx:alpine

# copy artifact build from the 'build environment'
COPY --from=build /app/dist /usr/share/nginx/html

COPY --from=build /usr/src/app/_site/ /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'

# expose port 80
#EXPOSE 80

# run nginx
#CMD ["nginx", "-g", "daemon off;"]

#This two lines would be useful if we are using apache but now we are using nginx
#COPY ./ports.conf /etc/apache2/ports.conf
#COPY ./apache.conf /etc/apache2/sites-enabled/000-default.conf

